input.onButtonPressed(Button.A, function () {
    music.playTone(698, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(698, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(698, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(750)
    music.playTone(659, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(659, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(698, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(659, music.beat(BeatFraction.Quarter))
    basic.pause(200)
    music.playTone(587, music.beat(BeatFraction.Quarter))
    basic.pause(200)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(750)
    music.playTone(349, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(349, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(349, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(740, music.beat(BeatFraction.Whole))
})
basic.forever(function () {
	
})
